# -*- coding: utf-8 -*-
"""secure_chat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHdK8hGBFMnriIOyWWRRoO99bOMd39fk
"""

!pip install cryptography

from cryptography.hazmat.primitives.asymmetric import dh
from cryptography.hazmat.primitives import hashes, hmac
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.fernet import Fernet
import base64


def generate_dh_parameters():
    return dh.generate_parameters(generator=2, key_size=2048)


def generate_key_pair(parameters):
    private_key = parameters.generate_private_key()
    public_key = private_key.public_key()
    return private_key, public_key


def derive_shared_key(private_key, peer_public_key):
    shared_secret = private_key.exchange(peer_public_key)

    key = HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=None,
        info=b"secure chat key",
    ).derive(shared_secret)

    return base64.urlsafe_b64encode(key)


def create_hmac(key, message):
    h = hmac.HMAC(key, hashes.SHA256())
    h.update(message)
    return h.finalize()


def verify_hmac(key, message, tag):
    h = hmac.HMAC(key, hashes.SHA256())
    h.update(message)
    h.verify(tag)


def main():
    print("My Secure Chat Project")

    parameters = generate_dh_parameters()

    alice_private, alice_public = generate_key_pair(parameters)
    bob_private, bob_public = generate_key_pair(parameters)

    alice_key = derive_shared_key(alice_private, bob_public)
    bob_key = derive_shared_key(bob_private, alice_public)

    print("Shared key created successfully!")

    message = input("Alice, enter message for Bob: ").encode()

    cipher = Fernet(alice_key)
    encrypted_message = cipher.encrypt(message)

    tag = create_hmac(alice_key, encrypted_message)

    print("\nEncrypted message:")
    print(encrypted_message)

    print("\nHMAC:")
    print(tag)

    tamper = input("\nDo you want to tamper message? (y/n): ")
    if tamper == "y":
        encrypted_message = encrypted_message[:-1] + b'0'

    try:
        verify_hmac(bob_key, encrypted_message, tag)
        decrypted_message = Fernet(bob_key).decrypt(encrypted_message)

        print("\nBob verified the message successfully!")
        print("Decrypted message:")
        print(decrypted_message.decode())

    except Exception:
        print("\n Message verification failed! It was modified.")


if __name__ == "__main__":
    main()